export enum LessonTypes{
    LEARNING="LEARNING",
    WARMUP="WARMUP",
    EXERCISE="EXERCISE",
    FINAL="FINAL"
}

export enum TopicTypes{
    LECTURE="LECTURE",
    V2TEXT="VIDEO_TO_TEXT",
    T2VIDEO="TEXT_TO_VIDEO",
    V2ACTION="VIDEO_TO_ACTION",
    T2ACTION="TEXT_TO_ACTION"
  }